### ISSUE TITLE
Publish Topcoder repo on PyPI

### ISSUE THREAD

**Issue by avidas** [asimihsan/challenges#2]
Firstly, thank you for the terrific effort on this repo. I am finding it rather useful for boilerplate generation and testing for topcoder problems. I was wondering if you would consider distributing the project (in particular, the topcoder parsing/boilerplate generation aspect) as a PyPI module for easier discoverability as there is no such module on PyPI currently. I would be willing to do the legwork to get the module ready if that would help.

**Comment by asimihsan** [comment]
Sorry this isn't clear but I just forked PyTopCoder from here: https://github.com/sbermeister/PyTopCoder

This isn't my project. I'm also very glad to be able to use PyTopCoder, but please raise an issue there instead. Thanks!

**Comment by asimihsan** [comment]
I'm leaving this issue open. Please paste in a link to the issue you raise on the main PyTopCoder project so I can keep an eye on it. Thanks!

**Comment by avidas** [comment]
Will do, thanks for letting me know

**Comment by avidas** [comment]
https://github.com/sbermeister/PyTopCoder/issues/5
